/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthOtpVerificationRouteImport } from './routes/auth/otp-verification'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as LayoutSubscriptionsRouteImport } from './routes/_layout/subscriptions'
import { Route as LayoutSubscription_idRouteImport } from './routes/_layout/subscription_$id'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutInsightsRouteImport } from './routes/_layout/insights'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthOtpVerificationRoute = AuthOtpVerificationRouteImport.update({
  id: '/otp-verification',
  path: '/otp-verification',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const LayoutSubscriptionsRoute = LayoutSubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSubscription_idRoute = LayoutSubscription_idRouteImport.update({
  id: '/subscription_$id',
  path: '/subscription_$id',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutInsightsRoute = LayoutInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/auth': typeof AuthRouteRouteWithChildren
  '/insights': typeof LayoutInsightsRoute
  '/settings': typeof LayoutSettingsRoute
  '/subscription_$id': typeof LayoutSubscription_idRoute
  '/subscriptions': typeof LayoutSubscriptionsRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/otp-verification': typeof AuthOtpVerificationRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/': typeof LayoutIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRouteRouteWithChildren
  '/insights': typeof LayoutInsightsRoute
  '/settings': typeof LayoutSettingsRoute
  '/subscription_$id': typeof LayoutSubscription_idRoute
  '/subscriptions': typeof LayoutSubscriptionsRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/otp-verification': typeof AuthOtpVerificationRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/': typeof LayoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/auth': typeof AuthRouteRouteWithChildren
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/insights': typeof LayoutInsightsRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/subscription_$id': typeof LayoutSubscription_idRoute
  '/_layout/subscriptions': typeof LayoutSubscriptionsRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/otp-verification': typeof AuthOtpVerificationRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/_layout/': typeof LayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/auth'
    | '/insights'
    | '/settings'
    | '/subscription_$id'
    | '/subscriptions'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/otp-verification'
    | '/auth/reset-password'
    | '/auth/signup'
    | '/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/insights'
    | '/settings'
    | '/subscription_$id'
    | '/subscriptions'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/otp-verification'
    | '/auth/reset-password'
    | '/auth/signup'
    | '/'
  id:
    | '__root__'
    | '/auth'
    | '/_layout'
    | '/_layout/insights'
    | '/_layout/settings'
    | '/_layout/subscription_$id'
    | '/_layout/subscriptions'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/otp-verification'
    | '/auth/reset-password'
    | '/auth/signup'
    | '/_layout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  LayoutRoute: typeof LayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/otp-verification': {
      id: '/auth/otp-verification'
      path: '/otp-verification'
      fullPath: '/auth/otp-verification'
      preLoaderRoute: typeof AuthOtpVerificationRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_layout/subscriptions': {
      id: '/_layout/subscriptions'
      path: '/subscriptions'
      fullPath: '/subscriptions'
      preLoaderRoute: typeof LayoutSubscriptionsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/subscription_$id': {
      id: '/_layout/subscription_$id'
      path: '/subscription_$id'
      fullPath: '/subscription_$id'
      preLoaderRoute: typeof LayoutSubscription_idRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/insights': {
      id: '/_layout/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof LayoutInsightsRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthOtpVerificationRoute: typeof AuthOtpVerificationRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthOtpVerificationRoute: AuthOtpVerificationRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface LayoutRouteChildren {
  LayoutInsightsRoute: typeof LayoutInsightsRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutSubscription_idRoute: typeof LayoutSubscription_idRoute
  LayoutSubscriptionsRoute: typeof LayoutSubscriptionsRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutInsightsRoute: LayoutInsightsRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutSubscription_idRoute: LayoutSubscription_idRoute,
  LayoutSubscriptionsRoute: LayoutSubscriptionsRoute,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRouteRoute: AuthRouteRouteWithChildren,
  LayoutRoute: LayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
